import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main study syllabus sidebar, excluding practice exams
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Core Services & Architecture',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'Compute'},
        {type: 'autogenerated', dirName: 'Containers'},
        {type: 'autogenerated', dirName: 'Database'},
        {type: 'autogenerated', dirName: 'Storage'},
        {type: 'autogenerated', dirName: 'Networking and Content Delivery'},
        {type: 'autogenerated', dirName: 'Security, Identity, and Compliance'},
      ]
    },
    {
      type: 'category',
      label: 'Management & Operations',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Management and Governance'},
        {type: 'autogenerated', dirName: 'Cloud Financial Management'},
        {type: 'autogenerated', dirName: 'Application Integration'},
        {type: 'autogenerated', dirName: 'Developer Tools'},
      ]
    },
    {
      type: 'category',
      label: 'Advanced & Specialized',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Analytics'},
        {type: 'autogenerated', dirName: 'Machine Learning'},
        {type: 'autogenerated', dirName: 'Migration and Transfer'},
        {type: 'autogenerated', dirName: 'Business Applications'},
        {type: 'autogenerated', dirName: 'End User Computing'},
        {type: 'autogenerated', dirName: 'Frontend Web and Mobile'},
        {type: 'autogenerated', dirName: 'Internet of Things'},
        {type: 'autogenerated', dirName: 'Media Services'},
        {type: 'autogenerated', dirName: 'Blockchain'},
      ]
    }
  ],

  // Organized Practice Exams sidebar with collapsible categories
  practiceSidebar: [
    'Practice Exams/SAP-C02 Mock Exam',
    {
      type: 'category',
      label: 'Mock Exam 1 (75 Questions)',
      collapsed: false,
      items: [
        'Practice Exams/SAP-C02 Mock Exam - Part 1',
        'Practice Exams/SAP-C02 Mock Exam - Part 2',
        'Practice Exams/SAP-C02 Mock Exam - Part 3',
      ]
    },
    {
      type: 'category',
      label: 'Mock Exam 2 (75 Questions)',
      collapsed: true,
      items: [
        'Practice Exams/SAP-C02 Mock Exam 2 - Part 1',
        'Practice Exams/SAP-C02 Mock Exam 2 - Part 2',
        'Practice Exams/SAP-C02 Mock Exam 2 - Part 3',
      ]
    },
    {
      type: 'category',
      label: 'Mock Exam 3 (75 Questions - Advanced)',
      collapsed: true,
      items: [
        'Practice Exams/SAP-C02 Mock Exam 3 - Part 1',
        'Practice Exams/SAP-C02 Mock Exam 3 - Part 2',
        'Practice Exams/SAP-C02 Mock Exam 3 - Part 3',
      ]
    }
  ]
};

export default sidebars;
