import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foundationSidebar: [
    {
      type: 'category',
      label: '00 / IT Foundation',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'foundation-bridge'},
      ]
    }
  ],

  // Main study syllabus sidebar, excluding practice exams
  tutorialSidebar: [
    'Solutions Architect Professional/intro',
    {
      type: 'category',
      label: 'Core Services & Architecture',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Compute'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Containers'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Database'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Storage'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Networking and Content Delivery'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Security, Identity, and Compliance'},
      ]
    },
    {
      type: 'category',
      label: 'Management & Operations',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Management and Governance'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Cloud Financial Management'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Application Integration'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Developer Tools'},
      ]
    },
    {
      type: 'category',
      label: 'Advanced & Specialized',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Analytics'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Machine Learning'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Migration and Transfer'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Business Applications'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/End User Computing'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Frontend Web and Mobile'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Internet of Things'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Media Services'},
        {type: 'autogenerated', dirName: 'Solutions Architect Professional/Blockchain'},
      ]
    }
  ],

  // Organized Practice Exams sidebar with collapsible categories
  practiceSidebar: [
    'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam',
    {
      type: 'category',
      label: 'Mock Exam 1 (75 Questions)',
      collapsed: false,
      items: [
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam - Part 1',
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam - Part 2',
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam - Part 3',
      ]
    },
    {
      type: 'category',
      label: 'Mock Exam 2 (75 Questions)',
      collapsed: true,
      items: [
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam 2 - Part 1',
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam 2 - Part 2',
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam 2 - Part 3',
      ]
    },
    {
      type: 'category',
      label: 'Mock Exam 3 (75 Questions - Advanced)',
      collapsed: true,
      items: [
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam 3 - Part 1',
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam 3 - Part 2',
        'Solutions Architect Professional/Practice Exams/SAP-C02 Mock Exam 3 - Part 3',
      ]
    }
  ],

  // Developer Associate DVA-C02 Study Sidebar
  dvaSidebar: [
    'Developer Associate/Study Plan',
    {
      type: 'category',
      label: 'AWS Fundamentals',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'Developer Associate/1-aws-fundamentals'},
      ]
    },
    {
      type: 'category',
      label: 'AWS Deep Dive',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Developer Associate/2-aws-deep-dive'},
      ]
    },
    {
      type: 'category',
      label: 'AWS Serverless',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Developer Associate/3-aws-serverless'},
      ]
    },
    {
      type: 'category',
      label: 'AWS Containers',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Developer Associate/4-aws-containers'},
      ]
    },
    {
      type: 'category',
      label: 'Other Topics',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Developer Associate/5-others'},
      ]
    }
  ],

  // Developer Associate DVA-C02 Practice Sidebar
  dvaPracticeSidebar: [
    'Developer Associate/Practice Exams/DVA-C02-Mock-Exam',
    {
      type: 'category',
      label: 'Mock Exam 1 (75 Questions)',
      collapsed: false,
      items: [
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-Part-1',
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-Part-2',
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-Part-3',
      ]
    },
    {
      type: 'category',
      label: 'Mock Exam 2 (75 Questions)',
      collapsed: true,
      items: [
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-2-Part-1',
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-2-Part-2',
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-2-Part-3',
      ]
    },
    {
      type: 'category',
      label: 'Mock Exam 3 (75 Questions - Advanced)',
      collapsed: true,
      items: [
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-3-Part-1',
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-3-Part-2',
        'Developer Associate/Practice Exams/DVA-C02-Mock-Exam-3-Part-3',
      ]
    }
  ]
};

export default sidebars;
